package top.liuyaqin.model;

import top.liuyaqin.model.base.BaseNewslogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newslogs extends BaseNewslogs<Newslogs> {
	public static final Newslogs dao = new Newslogs().dao();
}
