package top.liuyaqin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecommendations<M extends BaseRecommendations<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setJokeId(java.lang.String jokeId) {
		set("jokeId", jokeId);
	}

	public java.lang.String getJokeId() {
		return get("jokeId");
	}

	public void setDeriveTime(java.util.Date deriveTime) {
		set("recommendTime", deriveTime);
	}

	public java.util.Date getDeriveTime() {
		return get("recommendTime");
	}

	public void setFeedback(java.lang.Integer feedback) {
		set("feedback", feedback);
	}

	public java.lang.Integer getFeedback() {
		return get("feedback");
	}

	public void setDeriveAlgorithm(java.lang.Integer deriveAlgorithm) {
		set("algorithm", deriveAlgorithm);
	}

	public java.lang.Integer getDeriveAlgorithm() {
		return get("algorithm");
	}

}
